# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02a32bd8c456c242335987e3442b46ed4d6cb08ea8a852cac9b90f23ff5614907c984bb82daaefeffdaafb29f2368366f97fba629e97312e738a68e2276b846b

test:
  secret_key_base: e9b7c47ace91b5ff10fe31394277edf4ae1e814544136d87ec4473d2ffb0b3b51c4569e5ab8307ed6c4b67f9042bad3ee41a4ad94edada82dd853dabd91427fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
